param(
    [Parameter(Mandatory = $true)]
    [string]$SourceDirectory,
    [string]$OutputPath = "src/WG_SIGNON_ASSETS.inc"
)

$assets = [ordered]@{
    "WG_SignonApogee" = "SIGNON_APOGEE.BIN"
    "WG_SignonGT" = "SIGNON_GT.BIN"
    "WG_SignonID" = "SIGNON_ID.BIN"
    "WG_SignonActivision" = "SIGNON_ACTIVISION.BIN"
    "WG_SignonSpear" = "SIGNON_SPEAR.BIN"
}
$builder = [Text.StringBuilder]::new()
[void]$builder.AppendLine("/* Generated by tools/GENERATE_SIGNON_ASSETS.ps1. */")

foreach ($entry in $assets.GetEnumerator()) {
    $source = Join-Path $SourceDirectory $entry.Value
    $bytes = [IO.File]::ReadAllBytes($source)
    if ($bytes.Length -ne 64000) {
        throw "$source must contain exactly 64000 bytes"
    }
    [void]$builder.AppendLine("static const char $($entry.Key)[] =")
    for ($offset = 0; $offset -lt $bytes.Length; $offset += 32) {
        $last = [Math]::Min($offset + 31, $bytes.Length - 1)
        $values = $bytes[$offset..$last] | ForEach-Object { "\x{0:x2}" -f $_ }
        [void]$builder.AppendLine("    `"$($values -join '')`"")
    }
    [void]$builder.AppendLine("    ;")
    [void]$builder.AppendLine()
}

$resolved = [IO.Path]::GetFullPath((Join-Path (Get-Location) $OutputPath))
[IO.File]::WriteAllText($resolved, $builder.ToString(),
    [Text.UTF8Encoding]::new($false))
